# Generated by Django 4.1.7 on 2023-02-21 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=datetime.datetime(2023, 2, 21, 15, 48, 3, 244338, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
