# Generated by Django 4.1.7 on 2023-02-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
