# Generated by Django 4.1.7 on 2023-02-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_task_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.CharField(choices=[('P', 'Personal'), ('W', 'Work')], default='P', max_length=1),
        ),
    ]
