# Generated by Django 4.1.7 on 2023-02-26 01:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_alter_task_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_competion',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
