# Generated by Django 4.1.7 on 2023-02-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_task_date_competion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_competion',
            new_name='date_completion',
        ),
    ]
