# Generated by Django 4.1.7 on 2023-02-26 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0011_rename_date_competion_task_date_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_completion',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 1, 28, 52, 438286, tzinfo=datetime.timezone.utc)),
        ),
    ]
