# Generated by Django 4.1.7 on 2023-02-26 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0012_alter_task_date_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_completion',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 1, 29, 21, 502570, tzinfo=datetime.timezone.utc)),
        ),
    ]
