# Generated by Django 4.1.7 on 2023-03-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0014_alter_task_date_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_category',
            field=models.CharField(choices=[('personal', 'Personal'), ('work', 'Work')], default='personal', max_length=8),
        ),
    ]
